Write a NumPy program to get help on the add function.

In [ ]:
#Write a NumPy program to get help on the add function.
import numpy as np
print(np.info(np.add))


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [ ]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  **Calling ufuncs:** ``op(*x[, out], where=True, **kwargs)``
 |  
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array object(s) in whic

Q2.Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives.

In [ ]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Q3.Write a NumPy program to create a 3x3 identity matrix

In [ ]:
import numpy as np
array_2D=np.identity(3)
print('3x3 matrix:')
print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Q4.Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [ ]:
import numpy as np
x = np.zeros((4, 4))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


Q5.Write a NumPy program to create a 4x4 array, now create a new array from the said array swapping first and last, second and third columns

In [ ]:
import numpy as np 
nums = np.arange(16, dtype='int').reshape(-1, 4)
nums

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
print("Original array:")
print(nums)
print("\nNew array after swapping first and last columns of the said array:")
new_nums = nums[:, ::-1]
print(new_nums)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last columns of the said array:
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


Q6.Write a NumPy program to multiply two given arrays of the same size element-by-element.

In [ ]:
import numpy as np 
nums1 = np.array([[2, 5, 2],
              [1, 5, 5]])
nums2 = np.array([[5, 3, 4],
              [3, 2, 5]])

In [ ]:
nums1.shape

(2, 3)

In [ ]:
nums2.shape

(2, 3)

In [ ]:
print("Array1:") 
print(nums1)
print("Array2:") 
print(nums2)
print("\nMultiply said arrays of same size element-by-element:")
print(np.multiply(nums1, nums2))

Array1:
[[2 5 2]
 [1 5 5]]
Array2:
[[5 3 4]
 [3 2 5]]

Multiply said arrays of same size element-by-element:
[[10 15  8]
 [ 3 10 25]]


Q7.Write a NumPy program to move axes of an array to new positions. Other axes remain in their original order. 


[Expected Output:
(3, 4, 2)
(4, 2, 3)]


In [ ]:
import numpy as np
x = np.zeros((2, 3, 4))
print(np.moveaxis(x, 0, -1).shape)
print(np.moveaxis(x, -1, 0).shape)

(3, 4, 2)
(4, 2, 3)


Q8.Write a NumPy program to view inputs as arrays with at least two dimensions, three dimensions.


In [ ]:
import numpy as np
x = 10
print("View inputs as arrays with at least two dimensions:")
print(np.atleast_2d(x))
x = np.arange(4.0).reshape(2, 2)
print(np.atleast_2d(x))
print("View inputs as arrays with at least three dimensions:")
x =15
print(np.atleast_3d(x))
x = np.arange(3.0)
print(np.atleast_3d(x))



View inputs as arrays with at least two dimensions:
[[10]]
[[0. 1.]
 [2. 3.]]
View inputs as arrays with at least three dimensions:
[[[15]]]
[[[0.]
  [1.]
  [2.]]]


Q9.Write a NumPy program to create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
import numpy as np
x = np.zeros((5,5))
print("Original array:")
print(x)
print("Row values ranging from 0 to 4.")
x += np.arange(5)
print(x)


Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
4e2

400.0

Q10.Write a NumPy program to concatenate two 2-dimensional arrays.
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]


In [ ]:
arr1=[[0, 1, 3], [5, 7, 9]]
arr2=[[0, 2, 4], [6, 8, 10]]
arr3= np.c_[arr1,arr2]
print(arr3)
type(arr3)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


numpy.ndarray

In [ ]:
arr1=np.array([[0, 1, 3], [5, 7, 9]])
arr2=np.array([[0, 2, 4], [6, 8, 10]])
arr4= np.concatenate((arr1,arr2),1)
print(arr4)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


Q11 Write a NumPy program to convert 1-D arrays as columns into a 2-D array.Sample array: (10,20,30), (40,50,60)


In [ ]:
a=np.array((10,20,30))
b=np.array((40,50,60))
c=np.column_stack((a,b))
print(c)
c.shape

[[10 40]
 [20 50]
 [30 60]]


(3, 2)

Q12.Write a NumPy program to convert a NumPy array into Python list structure.


In [ ]:
import numpy as np
x= np.arange(6).reshape(3, 2)
print("Original array elements:")
print(x)
print("Array to list:")
a=x.tolist()
print(a)
type(a)


Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


list

Q13.Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).


In [ ]:
import numpy as np
x = np.arange(10)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(10))


[8 5 7 6 3 4 2 9 0 1]
Same result using permutation():
[8 3 4 0 9 2 7 1 5 6]


Q14.Write a NumPy program to replace all elements of a NumPy array that are greater than the specified array.[Expected Output: \
Original array: \
[[ 0.42436315 0.48558583 0.32924763] \
[ 0.7439979 0.58220701 0.38213418] \
[ 0.5097581 0.34528799 0.1563123 ]] \
Replace all elements of the said array with .5 which are greater than. 5 \
[[ 0.42436315 0.48558583 0.32924763] \
[ 0.5 0.5 0.38213418] \
[ 0.5 0.34528799 0.1563123 ]]] \

In [ ]:
import numpy as np
arr1=np.array([[ 0.42436315, 0.48558583 ,0.32924763],
[ 0.7439979, 0.58220701 ,0.38213418],
[ 0.5097581 ,0.34528799, 0.1563123 ]])
b=np.where(arr1>.5,.5,arr1)
print(b)

[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


Q15.Write a NumPy program to replace the negative values in a NumPy array with 0.

In [ ]:
arr1=np.array([[1,2,3],[-1,3,-6]])
arr2=np.where(arr1<0,0,arr1)
print(arr2)

[[1 2 3]
 [0 3 0]]
