<a href="https://colab.research.google.com/github/Somesh140/iNeauron_FSDS_Assignments/blob/main/Python_basic%20_programming_assignment/Programming_assignment_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q 1. Write a Python Program to Add two Matrices ?

In [1]:
#Ans:-
import numpy as np
arr = np.linspace(1,20,num=9)
arr1 = arr.reshape(3,3)
arr1

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [2]:
arr2 = arr1+1
arr2

array([[ 2.   ,  4.375,  6.75 ],
       [ 9.125, 11.5  , 13.875],
       [16.25 , 18.625, 21.   ]])

In [3]:
arr1 + arr2

array([[ 3.  ,  7.75, 12.5 ],
       [17.25, 22.  , 26.75],
       [31.5 , 36.25, 41.  ]])

Q 2. Write a Python Program to Multiply two Matrices ?

In [4]:
arr1@arr2

array([[126.234375, 150.28125 , 174.328125],
       [321.28125 , 396.09375 , 470.90625 ],
       [516.328125, 641.90625 , 767.484375]])

Q 3. Write a Python Program to transpose a Matrix ?

In [5]:
arr1.T

array([[ 1.   ,  8.125, 15.25 ],
       [ 3.375, 10.5  , 17.625],
       [ 5.75 , 12.875, 20.   ]])

4. Write a Python Program to Sort Words in Alphabetic Order?

In [6]:
# function to sort words in alphabetic order
def sort_words(string):
    words = string.split()
    sorted_words = sorted(words)
    return ' '.join(sorted_words)

# example string
string = "Python is a powerful programming language"

# call function to sort words
result = sort_words(string)

# print result
print(result)


Python a is language powerful programming


5. Write a Python Program to Remove Punctuation From a String?

In [10]:
import string
 
# define a string with punctuation
string_with_punctuations = "Hello, World! How are you?"
 
# remove the punctuation from the string
string_without_punctuations = string_with_punctuations.translate(str.maketrans("", "", string.punctuation))
 
# print the original and modified strings
print("Original String: ", string_with_punctuations)
print("Modified String: ", string_without_punctuations)


Original String:  Hello, World! How are you?
Modified String:  Hello World How are you
